### PR TITLE
Feat: New FPS/BPS calc

### PR DESCRIPTION
**Pull request by SnuffSocket**
New FPS/BPS calc: Handle zero division 'n use exponential moving average.
+Port over macOS "baudrate" from ETVR.

### CODE REVIEW

**Comment by dfgHiatus** [comment]
Running this on my PC spams a number of:

```
[INFO] Discarding the serial buffer (33501 bytes)
[INFO] Discarding the serial buffer (32852 bytes)
```

Logs on my end. Can you confirm this is/isn't the case for you? Using my COM5 port on a Babble Board, Win 10 PC

**Comment by dfgHiatus** [comment]
This seems to be the case on all my branches. I'll hold off until I can confirm this is the issue

**Comment by RamesTheGeneric** [comment]
> Running this on my PC spams a number of:
> 
> ```
> [INFO] Discarding the serial buffer (33501 bytes)
> [INFO] Discarding the serial buffer (32852 bytes)
> ```
> 
> Logs on my end. Can you confirm this is/isn't the case for you? Using my COM5 port on a Babble Board, Win 10 PC

This behavior is normal with openiris serial cameras.

**Review by RamesTheGeneric — APPROVED** [review]
Works 👍

**Pull request merged**
