### PR TITLE
Fix crash on model load and version increment

### PR DESCRIPTION
**Pull request by RamesTheGeneric**
App will now load the default model and alert the user when an incorrect file path is specified rather than crashing on startup.

Incremented the version number from 2.0.6 Alpha to 2.1.0 Beta

commit ```Fix low frame rate by lowering timeout time.``` has had it's changes reverted, I can't seem to figure out how to remove it from my repo.

### CODE REVIEW

**Comment by dfgHiatus** [comment]
Using this, it appears the user is prompted to choose a directory with the new "Browse" button. Is this the intended behavior? Or is the user expected to pick the model *file* as opposed to the *directory*

**Comment by RamesTheGeneric** [comment]
The user is intended to pick a model directory just like before, now there is simply a file browser to make picking the model file easier. A model path can still be specified like before.

**Comment by dfgHiatus** [comment]
> _"The user is intended to pick a model directory..."_
> _"...now there is ... a file browser to ... [pick a] model file..."_

Sorry, which one is this supposed to be here? Presently, if the user is expected to select a model file they are only able to choose a directory.

**Comment by RamesTheGeneric** [comment]
The models we distribute are stored in a specific directory structure. The way we have always specified the model is by the directory. This is no different.

**Comment by dfgHiatus** [comment]
Did some more testing here. Things are looking pretty good, I'll keep having a look at it, but I have no further comments at this time

**Comment by RamesTheGeneric** [comment]
I believe this is ready to merge then. I just need you to complete the review.

**Review by dfgHiatus — APPROVED** [review]

**Pull request merged**
