### PR TITLE
Fix: Camera address box size, comment out cam list print

### PR DESCRIPTION
**Pull request by SnuffSocket**

### CODE REVIEW

**Comment by dfgHiatus** [comment]
Hey there! I noticed your PR skips over some logic we added to account for if the image size changes at random - could you add some checks for this please? Thanks

**Comment by SnuffSocket** [comment]
> Hey there! I noticed your PR skips over some logic we added to account for if the image size changes at random - could you add some checks for this please? Thanks

Not sure what you mean by skipping logic, I had a quick look but mby I missed something? :/

**Comment by dfgHiatus** [comment]
I literally pasted this comment in the wrong issue, I am so sorry. Everything looks good here!

**Review by RamesTheGeneric — APPROVED** [review]
Looks good

**Pull request merged**
